### ISSUE TITLE
Add #include "Version.h"

### ISSUE THREAD

**Issue by max5555** [sblantipodi/platformio_version_increment#1]
It is worth mentioning in the readme that one have to include #include "Version.h" in the code beginning

**Comment by sblantipodi** [comment]
Hi,
thanks for your suggestion, I appreciate it.

This is the readme.

> In the `Version.h` file you'll have this:
> ```c++
> // AUTO GENERATED FILE FROM version_increment.py, DO NOT EDIT THIS FILE
> #ifndef VERSION
>   #define VERSION "0.1.0"
> #endif
> #ifndef BUILD_TIMESTAMP
>   #define BUILD_TIMESTAMP "2020-04-10 17:58:52.937616"
> #endif
> ```    
> use variables as you desire.

isn't this equals to "you have to #include "Version.h" ?

Thanks
Davide

**Comment by sblantipodi** [comment]
if you want you can create a pull request with "a better docs" and I will merge it.

thanks.
