### ISSUE TITLE
Upload success assumption re: auto increment

### ISSUE THREAD

**Issue by pfeerick** [sblantipodi/platformio_version_increment#3]
This doesn't take into account failed uploads (which I'm not sure is possible, but I thought worth mentioning so it it can either be investigated, or documented). 

Another minor assumption (not worth it's own issue) was the absence of an `include` folder will cause this to fail... found this out when adding to a pre-existing project where I'd deleted all the extraneous folders...

**Comment by sblantipodi** [comment]
Thanks for your feedback pfeerick.
I completely agree with all your points. 
I'm not sure if it's possible to know if the upload have failed.

I will fix the "issue of the include folder".

Thanks!!!

**Comment by sblantipodi** [comment]
Hi pfeerik, 
I fixed the `include` issue.

Now the script search for an include folder or for a `PLATFORMIO_INCLUDE_DIR` env variable, if there is no include folder or not environment variable it uses the root folder of the project.

PlatformIO does not offer an "hook" at the moment to know if the upload failed or not, at least via a script like this, I added a note in the docs just to inform users of the problem.

Thanks for your time.

**Comment by pfeerick** [comment]
I was going to suggest to just create the include folder, but that works very nicely indeed! ;) 

Yeah, I had a feeling that might be the case. I was actually wondering if it could be done as a post upload action - the theory being that post upload actions might not run if the upload fails... but need to test if that is actually the case.
