### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by gdampf** [sblantipodi/platformio_version_increment#8]
Trying the Version increment on an OTA-Project for ESP8266 is crashing compile compeletely with error message:

File C:\Users\guido\Documents\PlatformIO\Projects\XXX\platformio_version_increment\esp32_create_factory_bin_post.py  found where directory expected.

This occures in File "C:\Users\guido\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 181.

Can it be, this tool is just feasible for ESP32 and just, if programming is done over UAT?

**Comment by sblantipodi** [comment]
hi @gdampf 

please remove this line from your platformio.ini

`post:platformio_version_increment/esp32_create_factory_bin_post.py`

you don't need it when using ESP8266
